# Generated by Django 3.0.5 on 2020-04-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_imgplace_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgplace',
            name='guess_by',
            field=models.CharField(default='', max_length=255),
        ),
    ]
